/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { useFrame } from '@react-three/fiber'

type GLTFResult = GLTF & {
    nodes: {
        Head_1: THREE.Mesh
        Hat_Layer: THREE.Mesh
        Right_Arm: THREE.Mesh
        Right_Arm_Layer: THREE.Mesh
        Left_Arm: THREE.Mesh
        Left_Arm_Layer: THREE.Mesh
        Body_1: THREE.Mesh
        Body_Layer: THREE.Mesh
        Right_Leg: THREE.Mesh
        Right_Leg_Layer: THREE.Mesh
        Left_Leg: THREE.Mesh
        Left_Leg_Layer: THREE.Mesh
        cube: THREE.Mesh
        spruce: THREE.Mesh
        spruce_1: THREE.Mesh
        cube_1: THREE.Mesh
        spruce_2: THREE.Mesh
        spruce_3: THREE.Mesh
        cube_2: THREE.Mesh
        spruce_4: THREE.Mesh
        cube_3: THREE.Mesh
        cube_4: THREE.Mesh
        spruce_5: THREE.Mesh
        spruce_6: THREE.Mesh
        cube_5: THREE.Mesh
        spruce_7: THREE.Mesh
        spruce_8: THREE.Mesh
        cube_6: THREE.Mesh
        spruce_9: THREE.Mesh
        cube_7: THREE.Mesh
        cube_8: THREE.Mesh
        cube_9: THREE.Mesh
        cube_10: THREE.Mesh
        cube_11: THREE.Mesh
        cube_12: THREE.Mesh
        cube_13: THREE.Mesh
        cube_14: THREE.Mesh
        cube_15: THREE.Mesh
        cube_16: THREE.Mesh
        cube_17: THREE.Mesh
        cube_18: THREE.Mesh
        cube_19: THREE.Mesh
        cube_20: THREE.Mesh
        cube_21: THREE.Mesh
        cube_22: THREE.Mesh
        cube_23: THREE.Mesh
        cube_24: THREE.Mesh
        cube_25: THREE.Mesh
        cube_26: THREE.Mesh
        cube_27: THREE.Mesh
        cube_28: THREE.Mesh
        cube_29: THREE.Mesh
        cube_30: THREE.Mesh
        cube_31: THREE.Mesh
        cube_32: THREE.Mesh
        cube_33: THREE.Mesh
        cube_34: THREE.Mesh
        cube_35: THREE.Mesh
        cube_36: THREE.Mesh
        cube_37: THREE.Mesh
        cube_38: THREE.Mesh
        cube_39: THREE.Mesh
        cube_40: THREE.Mesh
        mesh_63: THREE.Mesh
        mesh_63_1: THREE.Mesh
        mesh_63_2: THREE.Mesh
        cube_42: THREE.Mesh
        mesh_65: THREE.Mesh
        mesh_65_1: THREE.Mesh
        mesh_65_2: THREE.Mesh
        cube_44: THREE.Mesh
    }
    materials: {}
}

type ActionName = 'jack'
type GLTFActions = Record<ActionName, THREE.AnimationAction>

export default function Animations(props: JSX.IntrinsicElements['group']) {
    const ref = useRef();
    const { nodes, animations } = useGLTF('/3d/animations.glb') as GLTFResult
    const { actions } = useAnimations<GLTFActions>(animations, ref)

    useEffect(() => {
        actions.jack.play();
    }, []);

    useFrame(({ clock }) => {
        ref.current.rotation.x = Math.PI / 180
    })

    return (
        <group ref={ref} {...props} dispose={null} setRotationFromAxisAngle={new THREE.Vector3(0, 0, 0), Math.PI / 180}>
            <group name="blockbench_export">
                <group>
                    <group name="bone" position={[0, 0, 1]}>
                        <group name="Body" position={[0, 0.75, 0]}>
                            <group name="Head" position={[0, 0.75, 0]}>
                                <mesh
                                    name="Head_1"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Head_1.geometry}
                                    material={nodes.Head_1.material}
                                    position={[0, -1.5, 0]}
                                />
                                <mesh
                                    name="Hat_Layer"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Hat_Layer.geometry}
                                    material={nodes.Hat_Layer.material}
                                    position={[0, -1.5, 0]}
                                />
                            </group>
                            <group name="RightArm" position={[0.313, 0.625, 0]}>
                                <mesh
                                    name="Right_Arm"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Right_Arm.geometry}
                                    material={nodes.Right_Arm.material}
                                    position={[-0.313, -0.625, 0]}
                                />
                                <mesh
                                    name="Right_Arm_Layer"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Right_Arm_Layer.geometry}
                                    material={nodes.Right_Arm_Layer.material}
                                    position={[-0.313, -0.625, 0]}
                                />
                            </group>
                            <group name="LeftArm" position={[-0.313, 0.625, 0]}>
                                <mesh
                                    name="Left_Arm"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Left_Arm.geometry}
                                    material={nodes.Left_Arm.material}
                                    position={[0.313, -1.375, 0]}
                                />
                                <mesh
                                    name="Left_Arm_Layer"
                                    castShadow
                                    receiveShadow
                                    geometry={nodes.Left_Arm_Layer.geometry}
                                    material={nodes.Left_Arm_Layer.material}
                                    position={[0.313, -1.375, 0]}
                                />
                            </group>
                            <mesh
                                name="Body_1"
                                castShadow
                                receiveShadow
                                geometry={nodes.Body_1.geometry}
                                material={nodes.Body_1.material}
                                position={[0, -0.75, 0]}
                            />
                            <mesh
                                name="Body_Layer"
                                castShadow
                                receiveShadow
                                geometry={nodes.Body_Layer.geometry}
                                material={nodes.Body_Layer.material}
                                position={[0, -0.75, 0]}
                            />
                        </group>
                        <group name="RightLeg" position={[0.119, 0.75, -0.016]}>
                            <mesh
                                name="Right_Leg"
                                castShadow
                                receiveShadow
                                geometry={nodes.Right_Leg.geometry}
                                material={nodes.Right_Leg.material}
                                position={[-0.119, -0.75, 0]}
                            />
                            <mesh
                                name="Right_Leg_Layer"
                                castShadow
                                receiveShadow
                                geometry={nodes.Right_Leg_Layer.geometry}
                                material={nodes.Right_Leg_Layer.material}
                                position={[-0.119, -0.75, 0]}
                            />
                        </group>
                        <group name="LeftLeg" position={[-0.119, 0.75, 0]}>
                            <mesh
                                name="Left_Leg"
                                castShadow
                                receiveShadow
                                geometry={nodes.Left_Leg.geometry}
                                material={nodes.Left_Leg.material}
                                position={[0.119, -0.75, 0]}
                            />
                            <mesh
                                name="Left_Leg_Layer"
                                castShadow
                                receiveShadow
                                geometry={nodes.Left_Leg_Layer.geometry}
                                material={nodes.Left_Leg_Layer.material}
                                position={[0.119, -0.75, 0]}
                            />
                        </group>
                    </group>
                    <group name="base" position={[-2.063, 0, 0.5]} rotation={[0, -Math.PI / 2, 0]}>
                        <group name="door1" position={[0.875, 0.25, -0.5]}>
                            <mesh
                                name="cube"
                                castShadow
                                receiveShadow
                                geometry={nodes.cube.geometry}
                                material={nodes.cube.material}
                                position={[-0.313, -0.125, 0.5]}
                            />
                            <mesh
                                name="spruce"
                                castShadow
                                receiveShadow
                                geometry={nodes.spruce.geometry}
                                material={nodes.spruce.material}
                                position={[-0.313, -0.125, 0.5]}
                            />
                            <mesh
                                name="spruce_1"
                                castShadow
                                receiveShadow
                                geometry={nodes.spruce_1.geometry}
                                material={nodes.spruce_1.material}
                                position={[-0.313, -0.125, 0.5]}
                            />
                            <mesh
                                name="cube_1"
                                castShadow
                                receiveShadow
                                geometry={nodes.cube_1.geometry}
                                material={nodes.cube_1.material}
                                position={[-0.313, 0.875, 0.5]}
                            />
                            <mesh
                                name="spruce_2"
                                castShadow
                                receiveShadow
                                geometry={nodes.spruce_2.geometry}
                                material={nodes.spruce_2.material}
                                position={[-0.313, 0.875, 0.5]}
                            />
                            <mesh
                                name="spruce_3"
                                castShadow
                                receiveShadow
                                geometry={nodes.spruce_3.geometry}
                                material={nodes.spruce_3.material}
                                position={[-0.313, -1.125, 0.5]}
                            />
                            <mesh
                                name="cube_2"
                                castShadow
                                receiveShadow
                                geometry={nodes.cube_2.geometry}
                                material={nodes.cube_2.material}
                                position={[-0.313, -1.125, 0.5]}
                            />
                            <mesh
                                name="spruce_4"
                                castShadow
                                receiveShadow
                                geometry={nodes.spruce_4.geometry}
                                material={nodes.spruce_4.material}
                                position={[-0.313, -1.125, 0.5]}
                            />
                            <mesh
                                name="cube_3"
                                castShadow
                                receiveShadow
                                geometry={nodes.cube_3.geometry}
                                material={nodes.cube_3.material}
                                position={[-1.188, -0.25, 0.5]}
                            />
                        </group>
                        <group name="door2" position={[-0.813, 3, -0.5]}>
                            <mesh
                                name="cube_4"
                                castShadow
                                receiveShadow
                                geometry={nodes.cube_4.geometry}
                                material={nodes.cube_4.material}
                                position={[0.5, -1.875, 0.5]}
                            />
                            <mesh
                                name="spruce_5"
                                castShadow
                                receiveShadow
                                geometry={nodes.spruce_5.geometry}
                                material={nodes.spruce_5.material}
                                position={[0.5, -1.875, 0.5]}
                            />
                            <mesh
                                name="spruce_6"
                                castShadow
                                receiveShadow
                                geometry={nodes.spruce_6.geometry}
                                material={nodes.spruce_6.material}
                                position={[0.5, -2.875, 0.5]}
                            />
                            <mesh
                                name="cube_5"
                                castShadow
                                receiveShadow
                                geometry={nodes.cube_5.geometry}
                                material={nodes.cube_5.material}
                                position={[0.5, -2.875, 0.5]}
                            />
                            <mesh
                                name="spruce_7"
                                castShadow
                                receiveShadow
                                geometry={nodes.spruce_7.geometry}
                                material={nodes.spruce_7.material}
                                position={[0.5, -2.875, 0.5]}
                            />
                            <mesh
                                name="spruce_8"
                                castShadow
                                receiveShadow
                                geometry={nodes.spruce_8.geometry}
                                material={nodes.spruce_8.material}
                                position={[0.5, -3.875, 0.5]}
                            />
                            <mesh
                                name="cube_6"
                                castShadow
                                receiveShadow
                                geometry={nodes.cube_6.geometry}
                                material={nodes.cube_6.material}
                                position={[0.5, -3.875, 0.5]}
                            />
                            <mesh
                                name="spruce_9"
                                castShadow
                                receiveShadow
                                geometry={nodes.spruce_9.geometry}
                                material={nodes.spruce_9.material}
                                position={[0.5, -3.875, 0.5]}
                            />
                            <mesh
                                name="cube_7"
                                castShadow
                                receiveShadow
                                geometry={nodes.cube_7.geometry}
                                material={nodes.cube_7.material}
                                position={[-0.375, -3, 0.5]}
                            />
                        </group>
                        <mesh
                            name="cube_8"
                            castShadow
                            receiveShadow
                            geometry={nodes.cube_8.geometry}
                            material={nodes.cube_8.material}
                            position={[0, 0, -0.5]}
                        />
                        <mesh
                            name="cube_9"
                            castShadow
                            receiveShadow
                            geometry={nodes.cube_9.geometry}
                            material={nodes.cube_9.material}
                            position={[0, 0, -0.5]}
                        />
                        <mesh
                            name="cube_10"
                            castShadow
                            receiveShadow
                            geometry={nodes.cube_10.geometry}
                            material={nodes.cube_10.material}
                            position={[0, 0, -0.5]}
                        />
                        <mesh
                            name="cube_11"
                            castShadow
                            receiveShadow
                            geometry={nodes.cube_11.geometry}
                            material={nodes.cube_11.material}
                            position={[-0.34, -0.481, -0.5]}
                            rotation={[0, 0, -Math.PI / 4]}
                        />
                        <mesh
                            name="cube_12"
                            castShadow
                            receiveShadow
                            geometry={nodes.cube_12.geometry}
                            material={nodes.cube_12.material}
                            position={[3.433, 2.613, -0.5]}
                            rotation={[0, 0, Math.PI / 4]}
                        />
                        <mesh
                            name="cube_13"
                            castShadow
                            receiveShadow
                            geometry={nodes.cube_13.geometry}
                            material={nodes.cube_13.material}
                            position={[0, 0, -0.5]}
                        />
                        <mesh
                            name="cube_14"
                            castShadow
                            receiveShadow
                            geometry={nodes.cube_14.geometry}
                            material={nodes.cube_14.material}
                            position={[0, 0, -0.5]}
                        />
                        <mesh
                            name="cube_15"
                            castShadow
                            receiveShadow
                            geometry={nodes.cube_15.geometry}
                            material={nodes.cube_15.material}
                            position={[-1.813, 0, -0.5]}
                        />
                        <mesh
                            name="cube_16"
                            castShadow
                            receiveShadow
                            geometry={nodes.cube_16.geometry}
                            material={nodes.cube_16.material}
                            position={[-1.813, 0, -0.5]}
                        />
                        <mesh
                            name="cube_17"
                            castShadow
                            receiveShadow
                            geometry={nodes.cube_17.geometry}
                            material={nodes.cube_17.material}
                            position={[0, 0, -0.5]}
                        />
                        <mesh
                            name="cube_18"
                            castShadow
                            receiveShadow
                            geometry={nodes.cube_18.geometry}
                            material={nodes.cube_18.material}
                            position={[0, 0, -0.5]}
                        />
                        <mesh
                            name="cube_19"
                            castShadow
                            receiveShadow
                            geometry={nodes.cube_19.geometry}
                            material={nodes.cube_19.material}
                            position={[0, 0, -0.5]}
                        />
                        <mesh
                            name="cube_20"
                            castShadow
                            receiveShadow
                            geometry={nodes.cube_20.geometry}
                            material={nodes.cube_20.material}
                            position={[0, 0, -0.5]}
                        />
                        <mesh
                            name="cube_21"
                            castShadow
                            receiveShadow
                            geometry={nodes.cube_21.geometry}
                            material={nodes.cube_21.material}
                            position={[0, 0, -0.5]}
                        />
                        <mesh
                            name="cube_22"
                            castShadow
                            receiveShadow
                            geometry={nodes.cube_22.geometry}
                            material={nodes.cube_22.material}
                            position={[0, 0, -0.5]}
                        />
                        <mesh
                            name="cube_23"
                            castShadow
                            receiveShadow
                            geometry={nodes.cube_23.geometry}
                            material={nodes.cube_23.material}
                            position={[0, 0, -0.5]}
                        />
                        <mesh
                            name="cube_24"
                            castShadow
                            receiveShadow
                            geometry={nodes.cube_24.geometry}
                            material={nodes.cube_24.material}
                            position={[0, 0, -0.5]}
                        />
                        <mesh
                            name="cube_25"
                            castShadow
                            receiveShadow
                            geometry={nodes.cube_25.geometry}
                            material={nodes.cube_25.material}
                            position={[0, 1, -0.5]}
                        />
                        <mesh
                            name="cube_26"
                            castShadow
                            receiveShadow
                            geometry={nodes.cube_26.geometry}
                            material={nodes.cube_26.material}
                            position={[0, 1, -0.5]}
                        />
                        <mesh
                            name="cube_27"
                            castShadow
                            receiveShadow
                            geometry={nodes.cube_27.geometry}
                            material={nodes.cube_27.material}
                            position={[0, -1, -0.5]}
                        />
                        <mesh
                            name="cube_28"
                            castShadow
                            receiveShadow
                            geometry={nodes.cube_28.geometry}
                            material={nodes.cube_28.material}
                            position={[0, -1, -0.5]}
                        />
                        <mesh
                            name="cube_29"
                            castShadow
                            receiveShadow
                            geometry={nodes.cube_29.geometry}
                            material={nodes.cube_29.material}
                            position={[0, 0, -0.5]}
                        />
                        <mesh
                            name="cube_30"
                            castShadow
                            receiveShadow
                            geometry={nodes.cube_30.geometry}
                            material={nodes.cube_30.material}
                            position={[0, 0, -0.5]}
                        />
                        <mesh
                            name="cube_31"
                            castShadow
                            receiveShadow
                            geometry={nodes.cube_31.geometry}
                            material={nodes.cube_31.material}
                            position={[0, 0, -0.5]}
                        />
                        <mesh
                            name="cube_32"
                            castShadow
                            receiveShadow
                            geometry={nodes.cube_32.geometry}
                            material={nodes.cube_32.material}
                            position={[-1.813, 0, -0.5]}
                        />
                        <mesh
                            name="cube_33"
                            castShadow
                            receiveShadow
                            geometry={nodes.cube_33.geometry}
                            material={nodes.cube_33.material}
                            position={[0, 0, -0.5]}
                        />
                        <mesh
                            name="cube_34"
                            castShadow
                            receiveShadow
                            geometry={nodes.cube_34.geometry}
                            material={nodes.cube_34.material}
                            position={[0, 0, -0.5]}
                        />
                        <mesh
                            name="cube_35"
                            castShadow
                            receiveShadow
                            geometry={nodes.cube_35.geometry}
                            material={nodes.cube_35.material}
                            position={[0, 0, -0.5]}
                        />
                        <mesh
                            name="cube_36"
                            castShadow
                            receiveShadow
                            geometry={nodes.cube_36.geometry}
                            material={nodes.cube_36.material}
                            position={[0, 0, -0.5]}
                        />
                        <mesh
                            name="cube_37"
                            castShadow
                            receiveShadow
                            geometry={nodes.cube_37.geometry}
                            material={nodes.cube_37.material}
                            position={[0, 0, -0.5]}
                        />
                        <mesh
                            name="cube_38"
                            castShadow
                            receiveShadow
                            geometry={nodes.cube_38.geometry}
                            material={nodes.cube_38.material}
                            position={[0, 0, -0.5]}
                        />
                        <mesh
                            name="cube_39"
                            castShadow
                            receiveShadow
                            geometry={nodes.cube_39.geometry}
                            material={nodes.cube_39.material}
                            position={[0, 0, -0.5]}
                        />
                    </group>
                    <group name="Scene" position={[-3.438, 3, -0.438]}>
                        <mesh
                            name="cube_40"
                            castShadow
                            receiveShadow
                            geometry={nodes.cube_40.geometry}
                            material={nodes.cube_40.material}
                            position={[4, -4, 3]}
                        />
                        <group name="cube_41" position={[0, -4, 3]}>
                            <mesh
                                name="mesh_63"
                                castShadow
                                receiveShadow
                                geometry={nodes.mesh_63.geometry}
                                material={nodes.mesh_63.material}
                            />
                            <mesh
                                name="mesh_63_1"
                                castShadow
                                receiveShadow
                                geometry={nodes.mesh_63_1.geometry}
                                material={nodes.mesh_63_1.material}
                            />
                            <mesh
                                name="mesh_63_2"
                                castShadow
                                receiveShadow
                                geometry={nodes.mesh_63_2.geometry}
                                material={nodes.mesh_63_2.material}
                            />
                        </group>
                        <mesh
                            name="cube_42"
                            castShadow
                            receiveShadow
                            geometry={nodes.cube_42.geometry}
                            material={nodes.cube_42.material}
                            position={[0, -4, -1]}
                        />
                        <group name="cube_43" position={[0, -4, -2]}>
                            <mesh
                                name="mesh_65"
                                castShadow
                                receiveShadow
                                geometry={nodes.mesh_65.geometry}
                                material={nodes.mesh_65.material}
                            />
                            <mesh
                                name="mesh_65_1"
                                castShadow
                                receiveShadow
                                geometry={nodes.mesh_65_1.geometry}
                                material={nodes.mesh_65_1.material}
                            />
                            <mesh
                                name="mesh_65_2"
                                castShadow
                                receiveShadow
                                geometry={nodes.mesh_65_2.geometry}
                                material={nodes.mesh_65_2.material}
                            />
                        </group>
                        <mesh
                            name="cube_44"
                            castShadow
                            receiveShadow
                            geometry={nodes.cube_44.geometry}
                            material={nodes.cube_44.material}
                            position={[8, -4, 3]}
                        />
                    </group>
                </group>
            </group>
        </group>
    )
}