/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/3d/giggles.glb')
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    actions.Falling.play();
  }, [actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="blockbench_export">
        <skinnedMesh
          name="giggles"
          geometry={nodes.giggles.geometry}
          material={nodes.giggles.material}
          skeleton={nodes.giggles.skeleton}
          position={[0, 0, -0.0406]}
          scale={[5, 5, 5]}>
          <primitive object={nodes.giggles_1} />
        </skinnedMesh>
      </group>
    </group>
  )
}

useGLTF.preload('/3d/giggles.gltf')
