/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('/3d/mewoster.glb');
  const { actions } = useAnimations(animations, group);
  const timeout = useRef<Timer | null>(null);

  useEffect(() => {
    actions.True_idle?.play();
  }, [actions]);

  return (
    <group ref={group} {...props} dispose={null}
      onDoubleClick={() => {
        actions.True_idle?.stop();
        actions.Hammer?.play();
        actions.Hammer?.setLoop(2200, 1);
        if (timeout.current) clearTimeout(timeout.current);
        timeout.current = setTimeout(() => actions.True_idle?.play(), actions.Hammer?.time)
      }}>
      <group name="blockbench_export">
        <group>
          <group name="main" position={[0, -0.063, 0]}>
            <group name="body" position={[0, 1.129, -0.052]}>
              <mesh
                name="cube"
                castShadow
                receiveShadow
                geometry={nodes.cube.geometry}
                material={nodes.cube.material}
                position={[0.063, 0.184, -0.26]}
              />
              <mesh
                name="cube_1"
                castShadow
                receiveShadow
                geometry={nodes.cube_1.geometry}
                material={nodes.cube_1.material}
                position={[0, 0.871, -0.01]}
                rotation={[-Math.PI / 8, 0, 0]}
              />
              <mesh
                name="cube_2"
                castShadow
                receiveShadow
                geometry={nodes.cube_2.geometry}
                material={nodes.cube_2.material}
                position={[0, 0.871, 0.052]}
              />
              <mesh
                name="cube_3"
                castShadow
                receiveShadow
                geometry={nodes.cube_3.geometry}
                material={nodes.cube_3.material}
                position={[0, 0.309, -0.26]}
              />
              <group name="arm_left" position={[-0.344, 0.809, -0.01]}>
                <mesh
                  name="cube_4"
                  castShadow
                  receiveShadow
                  geometry={nodes.cube_4.geometry}
                  material={nodes.cube_4.material}
                  position={[0.125, -0.5, -0.25]}
                />
                <mesh
                  name="cube_5"
                  castShadow
                  receiveShadow
                  geometry={nodes.cube_5.geometry}
                  material={nodes.cube_5.material}
                  position={[0.125, -0.438, -0.25]}
                />
                <group name="lowerarm_left" position={[0, -0.495, 0]}>
                  <mesh
                    name="cube_6"
                    castShadow
                    receiveShadow
                    geometry={nodes.cube_6.geometry}
                    material={nodes.cube_6.material}
                    position={[0.125, -0.38, -0.25]}
                  />
                  <mesh
                    name="cube_7"
                    castShadow
                    receiveShadow
                    geometry={nodes.cube_7.geometry}
                    material={nodes.cube_7.material}
                    position={[0.125, -0.88, -0.25]}
                  />
                  <group name="hand_left" position={[0, -0.442, 0]}>
                    <mesh
                      name="cube_8"
                      castShadow
                      receiveShadow
                      geometry={nodes.cube_8.geometry}
                      material={nodes.cube_8.material}
                      position={[0.125, -0.5, -0.25]}
                    />
                    <group
                      name="hammer"
                      position={[0.042, -0.063, 0.453]}
                      rotation={[-Math.PI / 2, 0, 0]}>
                      <mesh
                        name="cube_9"
                        castShadow
                        receiveShadow
                        geometry={nodes.cube_9.geometry}
                        material={nodes.cube_9.material}
                        position={[0.001, 1.953, 0]}
                      />
                      <mesh
                        name="cube_10"
                        castShadow
                        receiveShadow
                        geometry={nodes.cube_10.geometry}
                        material={nodes.cube_10.material}
                        position={[-0.011, 2.344, 0]}
                        rotation={[0, 0, Math.PI / 4]}
                      />
                      <mesh
                        name="cube_11"
                        castShadow
                        receiveShadow
                        geometry={nodes.cube_11.geometry}
                        material={nodes.cube_11.material}
                        position={[0.001, 1.953, 0]}
                      />
                      <mesh
                        name="cube_12"
                        castShadow
                        receiveShadow
                        geometry={nodes.cube_12.geometry}
                        material={nodes.cube_12.material}
                        position={[-0.011, 2.344, 0]}
                        rotation={[0, 0, Math.PI / 4]}
                      />
                      <mesh
                        name="cube_13"
                        castShadow
                        receiveShadow
                        geometry={nodes.cube_13.geometry}
                        material={nodes.cube_13.material}
                        position={[-0.011, 2.344, 0]}
                        rotation={[0, 0, Math.PI / 4]}
                      />
                    </group>
                  </group>
                </group>
              </group>
              <group name="arm_right" position={[0.344, 0.809, -0.01]}>
                <mesh
                  name="cube_14"
                  castShadow
                  receiveShadow
                  geometry={nodes.cube_14.geometry}
                  material={nodes.cube_14.material}
                  position={[-0.125, -0.5, -0.25]}
                />
                <mesh
                  name="cube_15"
                  castShadow
                  receiveShadow
                  geometry={nodes.cube_15.geometry}
                  material={nodes.cube_15.material}
                  position={[-0.125, -0.438, -0.25]}
                />
                <group name="lowerarm_right" position={[0, -0.495, 0]}>
                  <mesh
                    name="cube_16"
                    castShadow
                    receiveShadow
                    geometry={nodes.cube_16.geometry}
                    material={nodes.cube_16.material}
                    position={[-0.125, -0.38, -0.25]}
                  />
                  <mesh
                    name="cube_17"
                    castShadow
                    receiveShadow
                    geometry={nodes.cube_17.geometry}
                    material={nodes.cube_17.material}
                    position={[-0.125, -0.88, -0.25]}
                  />
                  <group name="hand_right" position={[0, -0.442, 0]}>
                    <mesh
                      name="cube_18"
                      castShadow
                      receiveShadow
                      geometry={nodes.cube_18.geometry}
                      material={nodes.cube_18.material}
                      position={[-0.125, -0.5, -0.25]}
                    />
                    <group name="bread" position={[-0.063, -0.219, 0.125]}>
                      <mesh
                        name="cube_19"
                        castShadow
                        receiveShadow
                        geometry={nodes.cube_19.geometry}
                        material={nodes.cube_19.material}
                        position={[0, 0.063, -0.25]}
                      />
                    </group>
                  </group>
                </group>
              </group>
              <group name="tail" position={[-0.022, 0.09, 0.105]}>
                <mesh
                  name="cube_20"
                  castShadow
                  receiveShadow
                  geometry={nodes.cube_20.geometry}
                  material={nodes.cube_20.material}
                  position={[0.084, 0.094, -0.197]}
                />
                <group name="middletail" position={[0, 0, 0.313]}>
                  <mesh
                    name="cube_21"
                    castShadow
                    receiveShadow
                    geometry={nodes.cube_21.geometry}
                    material={nodes.cube_21.material}
                    position={[0.084, 0.094, -0.197]}
                  />
                  <mesh
                    name="cube_22"
                    castShadow
                    receiveShadow
                    geometry={nodes.cube_22.geometry}
                    material={nodes.cube_22.material}
                    position={[0.109, -0.11, -0.043]}
                    rotation={[-Math.PI / 8, 0, 0]}
                  />
                  <mesh
                    name="cube_23"
                    castShadow
                    receiveShadow
                    geometry={nodes.cube_23.geometry}
                    material={nodes.cube_23.material}
                    position={[0.109, -0.305, -0.215]}
                    rotation={[Math.PI / 8, 0, 0]}
                  />
                  <mesh
                    name="cube_24"
                    castShadow
                    receiveShadow
                    geometry={nodes.cube_24.geometry}
                    material={nodes.cube_24.material}
                    position={[-0.11, 0.078, -0.043]}
                    rotation={[0, Math.PI / 8, 0]}
                  />
                  <mesh
                    name="cube_25"
                    castShadow
                    receiveShadow
                    geometry={nodes.cube_25.geometry}
                    material={nodes.cube_25.material}
                    position={[0.11, 0.109, -0.043]}
                    rotation={[0, -Math.PI / 8, 0]}
                  />
                  <group name="uppertail" position={[0, 0, 0.379]}>
                    <mesh
                      name="cube_26"
                      castShadow
                      receiveShadow
                      geometry={nodes.cube_26.geometry}
                      material={nodes.cube_26.material}
                      position={[0.084, 0.094, -0.138]}
                    />
                    <mesh
                      name="cube_27"
                      castShadow
                      receiveShadow
                      geometry={nodes.cube_27.geometry}
                      material={nodes.cube_27.material}
                      position={[0.084, 0.094, 0.299]}
                    />
                    <mesh
                      name="cube_28"
                      castShadow
                      receiveShadow
                      geometry={nodes.cube_28.geometry}
                      material={nodes.cube_28.material}
                      position={[-0.095, 0.094, -0.047]}
                      rotation={[0, Math.PI / 8, 0]}
                    />
                    <mesh
                      name="cube_29"
                      castShadow
                      receiveShadow
                      geometry={nodes.cube_29.geometry}
                      material={nodes.cube_29.material}
                      position={[0.094, -0.321, -0.219]}
                      rotation={[Math.PI / 8, 0, 0]}
                    />
                    <mesh
                      name="cube_30"
                      castShadow
                      receiveShadow
                      geometry={nodes.cube_30.geometry}
                      material={nodes.cube_30.material}
                      position={[0.095, 0.094, -0.047]}
                      rotation={[0, -Math.PI / 8, 0]}
                    />
                    <mesh
                      name="cube_31"
                      castShadow
                      receiveShadow
                      geometry={nodes.cube_31.geometry}
                      material={nodes.cube_31.material}
                      position={[0.094, -0.095, -0.047]}
                      rotation={[-Math.PI / 8, 0, 0]}
                    />
                  </group>
                </group>
              </group>
              <group name="head" position={[0, 0.935, -0.007]}>
                <mesh
                  name="cube_32"
                  castShadow
                  receiveShadow
                  geometry={nodes.cube_32.geometry}
                  material={nodes.cube_32.material}
                  position={[0.312, 0.265, -0.222]}
                  rotation={[0, -Math.PI / 8, 0]}
                />
                <mesh
                  name="cube_33"
                  castShadow
                  receiveShadow
                  geometry={nodes.cube_33.geometry}
                  material={nodes.cube_33.material}
                  position={[0.063, 0.015, 0.059]}
                />
                <mesh
                  name="cube_34"
                  castShadow
                  receiveShadow
                  geometry={nodes.cube_34.geometry}
                  material={nodes.cube_34.material}
                  position={[0.25, 0.249, 0.184]}
                  rotation={[0, Math.PI / 8, 0]}
                />
                <mesh
                  name="cube_35"
                  castShadow
                  receiveShadow
                  geometry={nodes.cube_35.geometry}
                  material={nodes.cube_35.material}
                  position={[0, -0.001, -0.378]}
                />
                <mesh
                  name="cube_36"
                  castShadow
                  receiveShadow
                  geometry={nodes.cube_36.geometry}
                  material={nodes.cube_36.material}
                  position={[-0.312, 0.265, -0.222]}
                  rotation={[0, Math.PI / 8, 0]}
                />
                <mesh
                  name="cube_37"
                  castShadow
                  receiveShadow
                  geometry={nodes.cube_37.geometry}
                  material={nodes.cube_37.material}
                  position={[-0.063, 0.015, 0.059]}
                />
                <mesh
                  name="cube_38"
                  castShadow
                  receiveShadow
                  geometry={nodes.cube_38.geometry}
                  material={nodes.cube_38.material}
                  position={[0.25, 0.249, -0.253]}
                  rotation={[0, Math.PI / 8, 0]}
                />
                <mesh
                  name="cube_39"
                  castShadow
                  receiveShadow
                  geometry={nodes.cube_39.geometry}
                  material={nodes.cube_39.material}
                  position={[-0.25, 0.249, 0.184]}
                  rotation={[0, -Math.PI / 8, 0]}
                />
                <mesh
                  name="cube_40"
                  castShadow
                  receiveShadow
                  geometry={nodes.cube_40.geometry}
                  material={nodes.cube_40.material}
                  position={[0.25, 0.499, -0.253]}
                  rotation={[-Math.PI / 8, 0, 0]}
                />
                <mesh
                  name="cube_41"
                  castShadow
                  receiveShadow
                  geometry={nodes.cube_41.geometry}
                  material={nodes.cube_41.material}
                  position={[-0.25, 0.249, -0.253]}
                  rotation={[0, -Math.PI / 8, 0]}
                />
                <mesh
                  name="cube_42"
                  castShadow
                  receiveShadow
                  geometry={nodes.cube_42.geometry}
                  material={nodes.cube_42.material}
                  position={[0, -0.001, 0.059]}
                />
                <group name="hair" position={[-0.25, 0.437, -0.316]}>
                  <mesh
                    name="cube_43"
                    castShadow
                    receiveShadow
                    geometry={nodes.cube_43.geometry}
                    material={nodes.cube_43.material}
                    position={[0.25, -0.188, 0.25]}
                  />
                  <mesh
                    name="cube_44"
                    castShadow
                    receiveShadow
                    geometry={nodes.cube_44.geometry}
                    material={nodes.cube_44.material}
                    position={[0.25, -0.125, 0.25]}
                  />
                </group>
                <group name="ear_left" position={[-0.143, 0.42, -0.055]} rotation={[0, 1.178, 0]}>
                  <mesh
                    name="cube_45"
                    castShadow
                    receiveShadow
                    geometry={nodes.cube_45.geometry}
                    material={nodes.cube_45.material}
                    position={[-0.023, -0.046, 0.26]}
                    rotation={[0, 0, Math.PI / 8]}
                  />
                  <mesh
                    name="cube_46"
                    castShadow
                    receiveShadow
                    geometry={nodes.cube_46.geometry}
                    material={nodes.cube_46.material}
                    position={[-0.056, 0.02, 0.26]}
                    rotation={[0, 0, -Math.PI / 8]}
                  />
                </group>
                <group name="ear_right" position={[0.143, 0.42, -0.055]} rotation={[0, -1.178, 0]}>
                  <mesh
                    name="cube_47"
                    castShadow
                    receiveShadow
                    geometry={nodes.cube_47.geometry}
                    material={nodes.cube_47.material}
                    position={[0.023, -0.046, 0.26]}
                    rotation={[0, 0, -Math.PI / 8]}
                  />
                  <mesh
                    name="cube_48"
                    castShadow
                    receiveShadow
                    geometry={nodes.cube_48.geometry}
                    material={nodes.cube_48.material}
                    position={[0.056, 0.02, 0.26]}
                    rotation={[0, 0, Math.PI / 8]}
                  />
                </group>
              </group>
            </group>
            <group name="leg_right" position={[0.125, 1.125, -0.063]}>
              <mesh
                name="cube_49"
                castShadow
                receiveShadow
                geometry={nodes.cube_49.geometry}
                material={nodes.cube_49.material}
                position={[-0.125, -0.25, -0.25]}
              />
              <group name="lowerleg_right" position={[0, -0.375, 0]}>
                <mesh
                  name="cube_50"
                  castShadow
                  receiveShadow
                  geometry={nodes.cube_50.geometry}
                  material={nodes.cube_50.material}
                  position={[-0.125, -0.438, -0.25]}
                />
                <group name="shoe_right" position={[0.001, -0.437, -0.005]}>
                  <mesh
                    name="cube_51"
                    castShadow
                    receiveShadow
                    geometry={nodes.cube_51.geometry}
                    material={nodes.cube_51.material}
                    position={[-0.001, 0.062, -0.12]}
                    rotation={[-Math.PI / 8, 0, 0]}
                  />
                  <mesh
                    name="cube_52"
                    castShadow
                    receiveShadow
                    geometry={nodes.cube_52.geometry}
                    material={nodes.cube_52.material}
                    position={[-0.117, -0.501, -0.245]}
                  />
                  <mesh
                    name="cube_53"
                    castShadow
                    receiveShadow
                    geometry={nodes.cube_53.geometry}
                    material={nodes.cube_53.material}
                    position={[-0.117, -0.501, -0.245]}
                  />
                  <mesh
                    name="cube_54"
                    castShadow
                    receiveShadow
                    geometry={nodes.cube_54.geometry}
                    material={nodes.cube_54.material}
                    position={[-0.117, -0.438, -0.245]}
                  />
                </group>
              </group>
            </group>
            <group name="leg_left" position={[-0.125, 1.125, -0.063]}>
              <mesh
                name="cube_55"
                castShadow
                receiveShadow
                geometry={nodes.cube_55.geometry}
                material={nodes.cube_55.material}
                position={[0.125, -0.25, -0.25]}
              />
              <group name="lowerleg_left" position={[0, -0.375, 0]}>
                <mesh
                  name="cube_56"
                  castShadow
                  receiveShadow
                  geometry={nodes.cube_56.geometry}
                  material={nodes.cube_56.material}
                  position={[0.125, -0.438, -0.25]}
                />
                <group name="shoe_left" position={[-0.001, -0.437, -0.005]}>
                  <mesh
                    name="cube_57"
                    castShadow
                    receiveShadow
                    geometry={nodes.cube_57.geometry}
                    material={nodes.cube_57.material}
                    position={[0.001, 0.062, -0.12]}
                    rotation={[-Math.PI / 8, 0, 0]}
                  />
                  <mesh
                    name="cube_58"
                    castShadow
                    receiveShadow
                    geometry={nodes.cube_58.geometry}
                    material={nodes.cube_58.material}
                    position={[0.117, -0.501, -0.245]}
                  />
                  <mesh
                    name="cube_59"
                    castShadow
                    receiveShadow
                    geometry={nodes.cube_59.geometry}
                    material={nodes.cube_59.material}
                    position={[0.117, -0.501, -0.245]}
                  />
                  <mesh
                    name="cube_60"
                    castShadow
                    receiveShadow
                    geometry={nodes.cube_60.geometry}
                    material={nodes.cube_60.material}
                    position={[0.117, -0.438, -0.245]}
                  />
                </group>
              </group>
            </group>
          </group>
          <group name="bomb" position={[-1.164, -0.001, -0.22]}>
            <mesh
              name="cube_61"
              castShadow
              receiveShadow
              geometry={nodes.cube_61.geometry}
              material={nodes.cube_61.material}
              position={[-0.242, 0.845, 0.002]}
              rotation={[0, 0, Math.PI / 8]}
            />
            <mesh
              name="cube_62"
              castShadow
              receiveShadow
              geometry={nodes.cube_62.geometry}
              material={nodes.cube_62.material}
              position={[-0.023, 0.563, 0.033]}
              rotation={[Math.PI / 8, 0, 0]}
            />
            <mesh
              name="cube_63"
              castShadow
              receiveShadow
              geometry={nodes.cube_63.geometry}
              material={nodes.cube_63.material}
              position={[0.227, 0.001, 0.22]}
            />
            <mesh
              name="cube_64"
              castShadow
              receiveShadow
              geometry={nodes.cube_64.geometry}
              material={nodes.cube_64.material}
              position={[0.258, 0.845, 0.002]}
              rotation={[0, 0, -Math.PI / 8]}
            />
            <mesh
              name="cube_outline"
              castShadow
              receiveShadow
              geometry={nodes.cube_outline.geometry}
              material={nodes.cube_outline.material}
              position={[-0.242, 0.845, 0.002]}
              rotation={[0, 0, Math.PI / 8]}
            />
            <mesh
              name="cube_outline_1"
              castShadow
              receiveShadow
              geometry={nodes.cube_outline_1.geometry}
              material={nodes.cube_outline_1.material}
              position={[0.258, 0.845, 0.002]}
              rotation={[0, 0, -Math.PI / 8]}
            />
            <mesh
              name="cube_outline_2"
              castShadow
              receiveShadow
              geometry={nodes.cube_outline_2.geometry}
              material={nodes.cube_outline_2.material}
              position={[0.227, 0.001, 0.22]}
            />
            <mesh
              name="cube_outline_3"
              castShadow
              receiveShadow
              geometry={nodes.cube_outline_3.geometry}
              material={nodes.cube_outline_3.material}
              position={[-0.023, 0.563, 0.033]}
              rotation={[Math.PI / 8, 0, 0]}
            />
            <group name="locator" position={[0.008, 0.282, 0.002]}>
              <group name="locator_1" scale={0.03} />
            </group>
            <group name="string" position={[-0.023, 0.616, 0.056]}>
              <mesh
                name="cube_65"
                castShadow
                receiveShadow
                geometry={nodes.cube_65.geometry}
                material={nodes.cube_65.material}
                position={[0, 0.063, 0.025]}
                rotation={[Math.PI / 8, 0, 0]}
              />
              <mesh
                name="cube_outline_4"
                castShadow
                receiveShadow
                geometry={nodes.cube_outline_4.geometry}
                material={nodes.cube_outline_4.material}
                position={[0, 0.063, 0.025]}
                rotation={[Math.PI / 8, 0, 0]}
              />
              <group name="string2" position={[0, 0.168, 0.097]}>
                <mesh
                  name="cube_66"
                  castShadow
                  receiveShadow
                  geometry={nodes.cube_66.geometry}
                  material={nodes.cube_66.material}
                  rotation={[-Math.PI / 8, 0, 0]}
                />
                <mesh
                  name="cube_outline_5"
                  castShadow
                  receiveShadow
                  geometry={nodes.cube_outline_5.geometry}
                  material={nodes.cube_outline_5.material}
                  rotation={[-Math.PI / 8, 0, 0]}
                />
              </group>
            </group>
            <group name="flame" position={[-0.023, 0.88, 0.383]}>
              <mesh
                name="cube_67"
                castShadow
                receiveShadow
                geometry={nodes.cube_67.geometry}
                material={nodes.cube_67.material}
                rotation={[-Math.PI / 8, 0, 0]}
              />
            </group>
          </group>
          <group name="gg" position={[0, 1.094, -0.938]}>
            <mesh
              name="cube_68"
              castShadow
              receiveShadow
              geometry={nodes.cube_68.geometry}
              material={nodes.cube_68.material}
              position={[0, 0.406, 0.063]}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/3d/mewoster.glb')
