name: Schedule Update

on:
  schedule:
    - cron: '0 0 */3 * *'  # Runs every 3 days at midnight
  workflow_dispatch:  # Allows manual triggering

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          export PATH="${HOME}/.bun/bin:$PATH"
      
      - name: Run update-all
        run: bun run update-all
      
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git checkout -b update-dependencies
          git add .
          git commit -m 'Update dependencies'
          git push --set-upstream origin update-dependencies
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update-dependencies
          title: 'Update dependencies'
          body: 'This PR updates dependencies.'
          labels: dependencies